version: '3.8'
services:
    app:
        container_name: login
        restart: always
        build: .
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - 3001:3001
networks:
    default:
        name: database_default
        external: true  