version: '3.8'
services:
    app:
        build: .
        command: npm start
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - 3002:3002
networks:
    default:
        name: database_default
        external: true   