version: "3.8"
services:
  app:
    container_name: app
    restart: always
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 3333:3333
networks:
  default:
    name: database_default
    external: true
