version: '3.8'
services:
    db:
        container_name: postgres
        image: postgres:14.1-alpine
        restart: always
        hostname: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        volumes:
            - db:/var/lib/postgresql/data
            - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
    db:
        driver: local
